name: Build PyPi Wheel
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build PyPi wheel
        uses: neuralmagic/nmstore/actions/pypi@pypi-test
      - name: Check status 
        run: echo ${{build.outputs.status}}
