name: Build PyPi Wheel
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.build.outputs.status }}
      commitid: ${{ steps.build.outputs.commitid }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build PyPi wheel
        id: build_pypi
        uses: neuralmagic/nmstore/actions/pypi@pypi-test