name: Build PyPi Wheel
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - 'release/**'
  push:
    branches:
      - main
  release:
    types: [created, published]
  schedule:
    - cron: '0 0 * * *'

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
  
# if not dev or release, will create a nightly build
# everything is pushed to internal unless created through a nightly scheduled cron job which creates the build or 
# missing release tag workflow/needs to be added in
env:
  INTERNAL: ${{ github.event_name != 'schedule' && github.event_name != 'release'}}
  RELEASE: ${{ github.event_name =='release' || (github.base_ref == 'release/**' && github.event_name == 'pull_request')}}
  DEV: ${{ github.base_ref == 'main' && github.event_name == 'pull_request'}}
  NAME: ${{ github.event.number }} 

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      wheel: ${{ steps.push-wheel.outputs.wheel }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to s3
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_WEBIDENTITY_FOR_GITHUB_ACTIONS }}
          aws-region: us-east-1 
      - name: Build PyPi Wheel
        id: build-wheel
        uses: neuralmagic/nm-actions/actions/pypi_build@pypi-actions
        with:
          dev: $DEV
          release: $RELEASE
          name: $NAME
      - name: Push to s3 bucket
        id: push-wheel
        uses: neuralmagic/nm-actions/actions/s3_push@pypi-actions
        with:
          filename: dist/*.whl
          internal: $INTERNAL

  pull_and_test:
    needs: build_and_push
    runs-on: ubuntu-latest  
    steps:
      - name: Login to s3
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_WEBIDENTITY_FOR_GITHUB_ACTIONS }}
          aws-region: us-east-1
      - name: Make directory for wheel
        run: |
             mkdir dist_s3
      - name: Pull from s3
        uses: neuralmagic/nm-actions/actions/s3_pull@pypi-actions
        with:
          filename: ${{ needs.build_and_push.outputs.wheel }}
          dst: dist_s3
      - name: Install Wheel
        run: |
             pip install dist_s3/*.whl
             pip install pytest
             pip install matplotlib
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test Wheel on Base Tests
        run: | 
             make test
    