name: Build PyPi Wheel
on:
  push:
    branches:
      - '*'
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build PyPi Wheel
        id: build_wheel
        uses: neuralmagic/nmstore/actions/pypi@pypi-test
      - name: Login to s3
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_WEBIDENTITY_FOR_GITHUB_ACTIONS }}
          aws-region: us-east-1
      - name: Push to s3
        uses: neuralmagic/nmstore/actions/s3@pypi-test
        with:
          filename: dist/*.whl
